### PR TITLE
Implement Microservice Template for Storage Service

### PR DESCRIPTION
**Pull request by MoritzHahn1337**
Adjusted the storage microservice to the service template

Closes https://jira.verbis.dkfz.de/browse/GDEV-132

### CODE REVIEW

**Review by ac-jorellanaf — APPROVED** [review]
That looks fine. Is that really everything needed to implement the template?

**Comment by MoritzHahn1337** [comment]
> 
> 
> That looks fine. Is that really everything needed to implement the template?

Apparently, my structure was already pretty close to the template. 
You can however take a look at the template and find out, if there are things that I missed.

**Review by ac-jorellanaf — COMMENTED** [review]
I think you are missing the setup.cfg file with an altered setup.py.

**Comment by MoritzHahn1337** [comment]
Fixed it.

**Review by ac-jorellanaf — APPROVED** [review]

**Pull request merged**
