### PR TITLE
feature/gdev-64

### PR DESCRIPTION
**Pull request by ac-jorellanaf**
https://jira.verbis.dkfz.de/browse/GDEV-64

### CODE REVIEW

**Comment by KerstenBreuer** [comment]
@ac-jorellanaf, this branch depends on Mpritz's PR #20?

**Comment by ac-jorellanaf** [comment]
> 
> 
> @ac-jorellanaf, this branch depends on Mpritz's PR #20?

Yes

**Comment by KerstenBreuer** [comment]
Could you please recreate this PR to be based on the current `dev`. Moritz's PR might still take some time but this one we could merge right away. (Just make sure to use the same gitattributes/editorconfig files as in the approved PR from the template repo).

**Comment by ac-jorellanaf** [comment]
> Could you please recreate this PR to be based on the current `dev`. Moritz's PR might still take some time but this one we could merge right away. (Just make sure to use the same gitattributes/editorconfig files as in the approved PR from the template repo).

Sure thing. I'll rebase the changes on this branch.

**Review by alamgirmani — APPROVED** [review]

**Pull request merged**
